FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit plotly pandas

COPY app.py /app/app.py
COPY docs /app/docs

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
