FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit plotly pandas google-generativeai python-dotenv

COPY app.py /app/app.py
COPY src /app/src
COPY docs /app/docs
COPY resume.txt /app/resume.txt
COPY sample_job.txt /app/sample_job.txt

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
